import type { Metadata } from "next";
import { Zen_Kaku_Gothic_Antique } from "next/font/google";
import "./globals.css";

const zen = Zen_Kaku_Gothic_Antique({
  variable: "--font-zens",
  weight: '700',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${zen.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
